# Generated by Django 3.1.2 on 2020-11-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20201113_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(help_text='Your question!', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='covid.questions'),
        ),
    ]
