# Generated by Django 3.1.2 on 2020-11-17 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20201117_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='covid.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to='covid.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default=1, help_text='Your question!', max_length=2048),
            preserve_default=False,
        ),
    ]
