# Generated by Django 3.1.2 on 2020-11-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20201117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='Answer', max_length=2048),
        ),
        migrations.AlterField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(default='Owner', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(default='Author', on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default='Questions', help_text='Your question!', max_length=2048),
        ),
    ]
