# Generated by Django 3.1.2 on 2020-11-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_remove_answers_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='ans',
        ),
    ]
